### ISSUE TITLE
accessing Custom Parameters sent from edx

### ISSUE THREAD

**Issue by njoliat** [mitodl/pylti#82]
When I create an LTI consumer component in the edX course editor, there's an option to enter custom parameters (see fig 1 below).  There's edX documentation on how to edit these parameters, but I can't figure out how to access them on the pylti side, in my flask app.  The [flask example app](https://github.com/mitodl/mit_lti_flask_sample) doesn't cover this.  Any ideas?
Thanks!

fig 1:
![screenshot-2018-1-10 nick lti test unit world music global rhythms studio](https://user-images.githubusercontent.com/565416/34899532-88bb681e-f7c7-11e7-86d2-ba5b87b40492.png)

**Comment by indagation** [comment]
@jolyonb, @pdpinch had mentioned that he thought that you may be able to give some insight into this.

**Comment by jolyonb** [comment]
I believe you can access the custom parameters using `request.form["custom_problemdata"]`. It's sent as part of the POST data.

**Comment by njoliat** [comment]
this works, thanks!  to clarify, for a parameter called `<name>`, you use `request.form["custom_<name>"]`

**Comment by KristofHorvath** [comment]
Are custom parameters missing from the LTI session? It's okay that I can fetch custom parameters from `request.form` with _custom_ prefix in the initial request. But are they disappear on the consecutive requests and are no longer available?

I would like to handle the problem ID in a custom parameter, but after displaying the problem, I cannot access the problem ID in the session variables when the user wants to grade. Of course, I could resend the problem ID as a hidden form field, but in this case, the user could maliciously modify the hidden content.

**Comment by jolyonb** [comment]
You're going to run into problems using session variables. The issue is that sessions are usually stored in cookies on the user's browser, and browsers don't like webpages in iframes setting cookies (which is how edX loads LTI pages). By default, safari blocks such cookies, which means that anybody on a mac can't use the LTI application. To get around this, you need to be super explicit about passing the session ID around through query parameters.

I don't know if this is your exact problem, but I recall it being an issue from a few years ago.

**Comment by jolyonb** [comment]
Also, I don't remember what is being stored in session data by this framework; you may just need to put stuff in there yourself if you want to keep it.

**Comment by KristofHorvath** [comment]
@jolyonb, thank you for your comment. I try to describe the whole story: When the LTI session is initialized, the consumer sends the problem ID, and my provider can display the problem. After the user solved it, he or she wants to grade, so clicks a button that loads another endpoint with `@lti(request='session', error=error, app=app)`. Because the LTI session (`lti.session`) does not include the custom parameters in this call, I cannot use the problem ID again to fetch the problem to grade.

You said, 'put stuff in there yourself.' What did you mean 'in there'? Is there a way in pylti to manage the data stored in the session?

**Comment by jolyonb** [comment]
The session variable is a generic flask variable. You can store data in it using normal flask methods. Look up the flask documentation to do so.

**Comment by KristofHorvath** [comment]
Thank you, it works properly. For some reason, I thought that the session is an integral part.
